version: '2'

services:
    refresh-compositesearch-with-vectors:
        build: .
        ports: 
            - "2233:2233"
        image: refresh-compositesearch-with-vectors
        container_name: refresh-compositesearch-with-vectors
        environment:
            - VIRTUAL_HOST=flaskapp.swap.io